# Generated by Django 4.0.4 on 2022-04-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField(help_text='Enter your ID', verbose_name='Enter EID')),
                ('ename', models.CharField(help_text='Enter Name:', max_length=10)),
                ('eemail', models.EmailField(max_length=254)),
                ('econtact', models.CharField(max_length=30)),
                ('Add_field', models.IntegerField(blank=True, default=-9)),
            ],
        ),
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'test1',
            },
        ),
    ]
