# Generated by Django 4.0.4 on 2022-04-26 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_choice_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='choice_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.test1'),
        ),
    ]
